---
title: "NAcc_setup_github"
output: html_document
date: "2026-09-02"
---
```{r load-pkgs}
library(readr)
library(dplyr)
library(tidyr)
library(psych)
```

```{r read_pds_data}
pds_y = read_tsv('/ABCDdatadir/phenotype/ph_y_pds.tsv',show_col_types = FALSE)
pds_USE <- filter(pds_y, session_id=='ses-01A')
table(pds_USE$session_id)

pds_USE = pds_USE[c("participant_id", "session_id", "ph_y_pds_001", "ph_y_pds_003", "ph_y_pds_002", "ph_y_pds__f_001", "ph_y_pds__f_002", "ph_y_pds__m_001", "ph_y_pds__m_002")]

pds_777 = pds_USE[pds_USE$ph_y_pds_001 == 777,]
pds_999 = pds_USE[pds_USE$ph_y_pds_001 == 999,]
pds_na1 = pds_USE[pds_USE$ph_y_pds__f_001 == 'n/a',]
pds_USE[pds_USE==777] <- NA
pds_USE[pds_USE==999] <- NA
pds_USE[pds_USE=='n/a'] <- NA

table(pds_USE$ph_y_pds_001)
table(pds_USE$ph_y_pds_002)
table(pds_USE$ph_y_pds_003)
table(pds_USE$ph_y_pds__f_001)
## Note menarche coded 0/1 instead of 1/4
table(pds_USE$ph_y_pds__f_002)
table(pds_USE$ph_y_pds__m_001)
table(pds_USE$ph_y_pds__m_002)

str(pds_USE)

pds_USE$ph_y_pds__f_001 <- as.numeric(pds_USE$ph_y_pds__f_001)
pds_USE$ph_y_pds__f_002 <- as.numeric(pds_USE$ph_y_pds__f_002)
pds_USE$ph_y_pds__m_001 <- as.numeric(pds_USE$ph_y_pds__m_001)
pds_USE$ph_y_pds__m_002 <- as.numeric(pds_USE$ph_y_pds__m_002)

str(pds_USE)

## Recode ph_y_pds__f_002 as 1/4 instead of 0/1
pds_USE$ph_y_pds__f_002_rc = ifelse(pds_USE$ph_y_pds__f_002==0,1,
                                    ifelse(pds_USE$ph_y_pds__f_002==1,4,NA))

table(pds_USE$ph_y_pds__f_002_rc)

#creating a PDS average score
pds_USE$pds_avg = rowMeans(pds_USE[,c("ph_y_pds_001","ph_y_pds_003", "ph_y_pds_002", "ph_y_pds__f_001", "ph_y_pds__f_002_rc", "ph_y_pds__m_001", "ph_y_pds__m_002")], na.rm=TRUE)

#subsetting and using complete cases
pds_USE=pds_USE[c("pds_avg", "participant_id", "session_id")]
pds_USE=pds_USE[complete.cases(pds_USE),]
count(pds_USE)

```

```{r read_ela_data}
#Done with the ELA+ code from from the Breslin et al. (2025). 
#I received this CSV after running the Breslin et al. (2025) ELAfromABCD_setup.Rmd and ELAfromABCD_ELAplus.Rmd codes while including the KSADS items for the 7.0 data release
elacba=read.csv("/ela_plus_abcd_new_7.0.csv")

#filtering baseline and subsetting
elacba <- filter(elacba, session_id=='ses-00A')
elacba=elacba[c("ela_plus", "participant_id", "session_id")]
count(elacba)

elacba=elacba[complete.cases(elacba),]
count(elacba)

final_combo = full_join(pds_USE, elacba, by=c('participant_id'))

sum(is.na(final_combo$pds_avg))
sum(is.na(final_combo$ela_plus))

final_combo=final_combo[complete.cases(final_combo),]
count(final_combo)


```

```{r read_fmri_data}
nacc_defl = read_tsv('/ABCDdatadir/phenotype/mr_y_rsfmri__corr__gpnet__aseg.tsv',show_col_types = FALSE)

nacc_filtered = filter(nacc_defl, session_id=="ses-02A")
nacc_filtered = dplyr::select(nacc_filtered, participant_id, session_id, mr_y_rsfmri__corr__gpnet__aseg__def__ab__lh_mean, mr_y_rsfmri__corr__gpnet__aseg__def__ab__rh_mean, mr_y_rsfmri__corr__gpnet__aseg__frp__ab__lh_mean, mr_y_rsfmri__corr__gpnet__aseg__frp__ab__rh_mean)

inclusion = read_tsv('/ABCDdatadir/phenotype/mr_y_qc__incl.tsv',show_col_types = FALSE)
inclusion_filtered <- inclusion[!duplicated(inclusion), ]
inclusion_filtered = filter(inclusion, mr_y_qc__incl__rsfmri_indicator==1, session_id=='ses-02A')
inclusion_filtered = dplyr::select(inclusion_filtered, participant_id, session_id, mr_y_qc__incl__rsfmri_indicator)

nacc_filtered=nacc_filtered[complete.cases(nacc_filtered),]
count(nacc_filtered)

final_combo = full_join(nacc_filtered, final_combo, by=('participant_id'))
final_combo=final_combo[complete.cases(final_combo),]
count(final_combo)

inclusion_filtered=inclusion_filtered[complete.cases(inclusion_filtered),]
count(inclusion_filtered)

final_combo = full_join(inclusion_filtered, final_combo, by=('participant_id'))
final_combo=final_combo[complete.cases(final_combo),]
count(final_combo)

```

```{r read_cov_rand}
covariates = read_tsv('/ABCDdatadir/phenotype/mr_y_adm__info.tsv',show_col_types = FALSE)
scannerid = filter(covariates, session_id=='ses-02A')
scannerid_USE = dplyr::select(scannerid, participant_id, session_id, mr_y_adm__info__dev_serial)
table(scannerid_USE$mr_y_adm__info__dev_serial)

##excluding youth who were scanned on these two scanners due to very low sample sizes
scannerid_USE = dplyr::filter(scannerid_USE, mr_y_adm__info__dev_serial != "d744819bc6e66ac33dd7f1b681b37c6f386f08404e36ccb99f017f227f97b55e")
scannerid_USE = dplyr::filter(scannerid_USE, mr_y_adm__info__dev_serial != "52bbdd010b4a1d3f89ce9eebbfd81dd6ea986bcd68830988bf883b2c12625500")

table(scannerid_USE$mr_y_adm__info__dev_serial)

## Recoding scanner names so they're not so long
scannerid_USE$scanner_id <- factor(paste0("scanner", as.numeric(as.factor(scannerid_USE$mr_y_adm__info__dev_serial))))

scannerid_USE=scannerid_USE[complete.cases(scannerid_USE),]
count(scannerid_USE)

final_combo = inner_join(scannerid_USE, final_combo, by=('participant_id'))
final_combo=final_combo[complete.cases(final_combo),]
count(final_combo)

#Including age & site
age_siteid = read_tsv('/ABCDdatadir/phenotype/ab_g_dyn.tsv',show_col_types = FALSE)
age_siteid = age_siteid[c("participant_id", "session_id", "ab_g_dyn__visit_age", "ab_g_dyn__design_site")] 
site_id = filter(age_siteid, session_id=='ses-00A')
site_id_USE = dplyr::select(site_id, participant_id, session_id, ab_g_dyn__design_site)
site_id_USE$ab_g_dyn__design_site = as.factor(site_id_USE$ab_g_dyn__design_site)

final_combo = full_join(site_id_USE, final_combo, by=('participant_id'))
final_combo=final_combo[complete.cases(final_combo),]
count(final_combo)

age = filter(age_siteid, session_id=='ses-02A')
age_USE = dplyr::select(age, participant_id, session_id, ab_g_dyn__visit_age)

age_USE=age_USE[complete.cases(age_USE),]
table(age_USE$session_id)

final_combo = full_join(age_USE, final_combo, by=('participant_id'))
final_combo=final_combo[complete.cases(final_combo),]
count(final_combo)

demo_USE = read_tsv('/ABCDdatadir/phenotype/ab_g_stc.tsv',show_col_types = FALSE)
demo_USE = dplyr::select(demo_USE, participant_id, ab_g_stc__design_id__fam, ab_g_stc__cohort_sex, ab_g_stc__cohort_ethnrace__leg)

#Centering sex
demo_USE$ab_g_stc__cohort_sex = scale(demo_USE$ab_g_stc__cohort_sex, center = TRUE, scale = FALSE)
table(demo_USE$ab_g_stc__cohort_sex)
demo_USE$sex=demo_USE$ab_g_stc__cohort_sex

demo_USE=demo_USE[complete.cases(demo_USE),]
count(demo_USE)

edu = read_tsv('/ABCDdatadir/phenotype/ab_p_demo.tsv',show_col_types = FALSE)
edu = edu[c("participant_id", "session_id", "ab_p_demo__edu__slf_001")] 
edu = filter(edu, session_id=='ses-00A')
edu=edu[complete.cases(edu),]
table(edu$session_id)

demo_USE = full_join(edu, demo_USE, by=c('participant_id'))
table(demo_USE$session_id)

#Changing Family ID to a factor
demo_USE$ab_g_stc__design_id__fam = as.factor(demo_USE$ab_g_stc__design_id__fam)

#Changing race/ethnicity & sex as factors
demo_USE$race = ifelse(demo_USE$ab_g_stc__cohort_ethnrace__leg ==1, "Hispanic", demo_USE$ab_g_stc__cohort_ethnrace__leg)
demo_USE$race = ifelse(demo_USE$race ==2, "White", demo_USE$race)
demo_USE$race = ifelse(demo_USE$race ==3, "Black", demo_USE$race)
demo_USE$race = ifelse(demo_USE$race ==4, "Asian", demo_USE$race)
demo_USE$race = ifelse(demo_USE$race ==13, "Other", demo_USE$race)
table(demo_USE$race)

demo_USE$race = as.factor(demo_USE$race)
demo_USE$race <- factor(demo_USE$race,
                      levels = c("White", "Hispanic", "Black", "Other", "Asian"))
table(demo_USE$race)

#Recoding Parent Education
#Recoding for numbers 0-8 to be #1 for less than high school education
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 0] <- 1
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 1] <- 1
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 2] <- 1
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 3] <- 1
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 4] <- 1
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 5] <- 1
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 6] <- 1
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 7] <- 1
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 8] <- 1

#Recoding for numbers 9-12 to be #2 for some high school
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 9] <- 2
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 10] <- 2
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 11] <- 2
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 12] <- 2

#Recoding for numbers 13-14 to be #3 for high school graduate or GED
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 13] <- 3
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 14] <- 3

#Recoding for numbers 15-17 to be #4 for between hs grad and bachelor
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 15] <- 4
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 16] <- 4
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 17] <- 4

#Recoding for number 18 to be #5 for bachelor's degree
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 18] <- 5

#Recoding for number 19-20 to be #6 for master's degree and professional
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 19] <- 6

#Recoding for number 21 to be #7 for doctorate
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 20] <- 7
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 21] <- 7

#kara's reccomendation for recoding the NA's so that they are not included in the final sample size for demographic information
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 777] <- NA
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 999] <- NA
demo_USE$ab_p_demo__edu__slf_001[demo_USE$ab_p_demo__edu__slf_001 == 'n/a'] <- NA
table(demo_USE$session_id)

demo_USE=demo_USE[complete.cases(demo_USE),]
table(demo_USE$session_id)

final_combo = full_join(demo_USE, final_combo, by=('participant_id'))
final_combo=final_combo[complete.cases(final_combo),]
count(final_combo)

#Including BMI
bmi = read_tsv('/ABCDdatadir/phenotype/ph_y_anthr.tsv',show_col_types = FALSE)
bmi = bmi[c("participant_id", "session_id", "ph_y_anthr__height_mean", "ph_y_anthr__weight_mean")] 
bmi = filter(bmi, session_id=='ses-00A')

bmi$ph_y_anthr__height_mean = as.numeric(bmi$ph_y_anthr__height_mean)
bmi$ph_y_anthr__weight_mean = as.numeric(bmi$ph_y_anthr__weight_mean)
bmi$bmi <- (bmi$ph_y_anthr__weight_mean / (bmi$ph_y_anthr__height_mean^2)) * 703

bmi=bmi[complete.cases(bmi),]
table(bmi$session_id)
describe(bmi$bmi)

final_combo = full_join(bmi, final_combo, by=('participant_id'))
final_combo=final_combo[complete.cases(final_combo),]
count(final_combo)

table(final_combo$ela_plus)

count(final_combo)

#making ACE score, PDS avg, and parent education numeric
final_combo$ela_plus = as.numeric(final_combo$ela_plus)
final_combo$pds_avg = as.numeric(final_combo$pds_avg)
final_combo$ab_p_demo__edu__slf_001 = as.numeric(final_combo$ab_p_demo__edu__slf_001)

final_combo = final_combo[, c("mr_y_rsfmri__corr__gpnet__aseg__def__ab__lh_mean", "mr_y_rsfmri__corr__gpnet__aseg__def__ab__rh_mean", "mr_y_rsfmri__corr__gpnet__aseg__frp__ab__lh_mean", "mr_y_rsfmri__corr__gpnet__aseg__frp__ab__rh_mean", "participant_id", "scanner_id", "ab_g_dyn__visit_age", "race", "sex", "ab_p_demo__edu__slf_001", "ab_g_stc__design_id__fam", "ela_plus", "pds_avg", "bmi")]

final_combo = final_combo[complete.cases(final_combo),]
final_combo = data.frame(final_combo)
count(final_combo)

#Descriptive information
table(final_combo$race)
contrasts(final_combo$race)

describe(final_combo$pds_avg)
describe(final_combo$ela_plus)
table(final_combo$ela_plus)

describe(final_combo$ab_g_dyn__visit_age)
describe(final_combo$ab_p_demo__edu__slf_001)
table(final_combo$ab_p_demo__edu__slf_001)
describe(final_combo$bmi)
describe(final_combo$sex)
table(final_combo$sex)

describe(final_combo$mr_y_rsfmri__corr__gpnet__aseg__def__ab__lh_mean)
describe(final_combo$mr_y_rsfmri__corr__gpnet__aseg__def__ab__rh_mean)
describe(final_combo$mr_y_rsfmri__corr__gpnet__aseg__frp__ab__lh_mean)
describe(final_combo$mr_y_rsfmri__corr__gpnet__aseg__frp__ab__rh_mean)


```

```{r standardizing}
#Recoding for ACEs 1,2,3, and >=4
final_combo$ela_plus[final_combo$ela_plus == 0] <- 0
final_combo$ela_plus[final_combo$ela_plus == 1] <- 1
final_combo$ela_plus[final_combo$ela_plus == 2] <- 2
final_combo$ela_plus[final_combo$ela_plus == 3] <- 3
final_combo$ela_plus[final_combo$ela_plus >= 4] <- 4
table(final_combo$ela_plus)

final_combo$pds_avg.z = scale(final_combo$pds_avg, center = TRUE, scale = TRUE)
final_combo$bmi.z = scale(final_combo$bmi, center = TRUE, scale = TRUE)
final_combo$age.z = scale(final_combo$ab_g_dyn__visit_age, center = TRUE, scale = TRUE)
final_combo$edu.z = scale(final_combo$ab_p_demo__edu__slf_001, center = TRUE, scale = TRUE)
final_combo$ela.z = scale(final_combo$ela_plus, center = TRUE, scale = TRUE)
final_combo$dmn_lh.z = scale(final_combo$mr_y_rsfmri__corr__gpnet__aseg__def__ab__lh_mean, center = TRUE, scale = TRUE)
final_combo$dmn_rh.z = scale(final_combo$mr_y_rsfmri__corr__gpnet__aseg__def__ab__rh_mean, center = TRUE, scale = TRUE)
final_combo$frp_lh.z = scale(final_combo$mr_y_rsfmri__corr__gpnet__aseg__frp__ab__lh_mean, center = TRUE, scale = TRUE)
final_combo$frp_rh.z = scale(final_combo$mr_y_rsfmri__corr__gpnet__aseg__frp__ab__rh_mean, center = TRUE, scale = TRUE)

table(final_combo$ela.z)

write.csv(final_combo, "final_combo_7.0_KK.csv")
```
