---
title: "Nacc_Mediation_githubedition"
author: "gibby"
date: "2025-02-13"
output: html_document
---
```{r Set up}

#Prior to running, will need to find and replace "ABCDdatadir" with the path to the directory where you can access the ABCD data.

```

```{r Packages, include=FALSE}

library(effectsize)
library(dplyr)
library(psych)
library(tidyverse)
library(ggplot2)
library(lme4)
library(lmerTest)
library(reshape2)
library(writexl)
library(janitor)
library(rainbow)
library(tidyr)
library(mediation)
library(standardize)

```

```{r Puberty}

pds_y = read.csv("ABCDdatadir/core/physical-health/ph_y_pds.csv",header=TRUE,stringsAsFactors = FALSE)
table(pds_y$eventname)

#filtering and subsetting by Year 1 and for each variable
pds_USE <- filter(pds_y, eventname=='1_year_follow_up_y_arm_1')
pds_USE = pds_USE[c("src_subject_id", "eventname", "pds_ht2_y", "pds_skin2_y", "pds_bdyhair_y", "pds_f4_2_y", "pds_f5_y", "pds_m4_y", "pds_m5_y")]

pds_777 = pds_USE[pds_USE$pds_ht2_y == 777,]
pds_999 = pds_USE[pds_USE$pds_ht2_y == 999,]
pds_USE[pds_USE==777] <- NA
pds_USE[pds_USE==999] <- NA

#creating a PDS average score
pds_USE$pds_avg = rowMeans(pds_USE[,c("pds_ht2_y","pds_skin2_y", "pds_bdyhair_y", "pds_f4_2_y", "pds_f5_y", "pds_m4_y", "pds_m5_y")], na.rm=TRUE)

#subsetting 
pds_USE=pds_USE[c("pds_avg", "src_subject_id", "eventname")]
pds_USE=pds_USE[complete.cases(pds_USE),]
count(pds_USE)

```

```{r ELA}

#Importing KSADs Parent report 
KSADs_ptsd <- read.csv("ABCDdatadir/core/mental-health/mh_p_ksads_ptsd.csv",stringsAsFactors = TRUE, na.strings = "NA")
table(KSADs_ptsd$eventname)

#including only Baseline
ptsd_USE <- filter(KSADs_ptsd, eventname=='baseline_year_1_arm_1')

#Pulling the Bullying Item at baseline and subsetting for only that item
bully <- read.csv("ABCDdatadir/core/mental-health/mh_p_ksads_bg.csv",stringsAsFactors = TRUE, na.strings = "NA")
bully_filtered <- filter(bully, eventname=='baseline_year_1_arm_1')
bully_filtered = bully_filtered[c("src_subject_id", "eventname", "kbi_p_c_bully")]

#Re-coding the bullying item from (1=Yes, 2=No) to (0=No, 1=Yes)
#Coded backward in original data
bully_recode <- bully_filtered
bully_recode[bully_recode==2] <- 0   
table(bully_recode$kbi_p_c_bully)

#Check to make sure re-coding worked
sum(bully_recode == "0")
sum(bully_filtered =="2")

#Importing Demographics Survey data for ELA
ABCD_demo <- read.csv("ABCDdatadir/core/abcd-general/abcd_p_demo.csv",stringsAsFactors = TRUE, na.strings = "NA")
demo_filtered <- filter(ABCD_demo, eventname=='baseline_year_1_arm_1')
demo_USE = dplyr::select(demo_filtered, src_subject_id, eventname, demo_fam_exp1_v2, demo_fam_exp2_v2, demo_fam_exp3_v2, demo_fam_exp4_v2, demo_fam_exp5_v2, demo_fam_exp6_v2, demo_fam_exp7_v2)

#Creating & Cleaning ACEs.df
ELA_ACEs <- full_join(ptsd_USE, bully_recode, demo_USE, by='src_subject_id')
names(ELA_ACEs)[names(ELA_ACEs)=='eventname.x'] <- 'eventname'
names(ELA_ACEs)[names(ELA_ACEs)=='eventname.y'] <- 'eventname.Demo'
ELA_ACEs[ELA_ACEs==777] <- NA
ELA_ACEs <- ELA_ACEs %>% 
  mutate(ACE_score=rowSums(across(where(is.numeric))))

#Recoding for ACEs >=4
ELA_ACEs$ACE_score[ELA_ACEs$ACE_score >= 4] <- 4

#centering the ELA variable
ELA_ACEs$ACE_score = scale(ELA_ACEs$ACE_score, center = TRUE, scale = FALSE)
table(ELA_ACEs$ACE_score)

#Checking new ACEs.df
length(unique(ELA_ACEs$src_subject_id))
str(ELA_ACEs)
summary(ELA_ACEs)
ELA_ACEs %>%
  summarise(
     mean(ACE_score, na.rm=TRUE),
     sd(ACE_score, na.rm=TRUE),
     median(ACE_score, na.rm=TRUE))

#subsetting
ELA_ACEs=ELA_ACEs[c("ACE_score", "src_subject_id", "eventname")]
ELA_ACEs=ELA_ACEs[complete.cases(ELA_ACEs),]
count(ELA_ACEs)

final_combo = full_join(pds_USE, ELA_ACEs, by=('src_subject_id'))
final_combo=final_combo[complete.cases(final_combo),]
count(final_combo)

```

```{r Func Data Reading}

#reading in the functional data
nacc_defl = read.csv("ABCDdatadir/core/imaging/mri_y_rsfmr_cor_gp_aseg.csv",header=TRUE,stringsAsFactors = FALSE)
table(nacc_defl$eventname)

nacc_filtered = filter(nacc_defl, eventname=="2_year_follow_up_y_arm_1")
nacc_filtered = dplyr::select(nacc_filtered, src_subject_id, eventname, rsfmri_cor_ngd_df_scs_aalh, rsfmri_cor_ngd_df_scs_aarh, rsfmri_cor_ngd_fopa_scs_aalh, rsfmri_cor_ngd_fopa_scs_aarh)

#reading in the inclusion criteria
inclusion = read.csv("ABCDdatadir/core/imaging/mri_y_qc_incl.csv")
table(inclusion$eventname)

inclusion_filtered <- inclusion[!duplicated(inclusion), ]
inclusion_filtered = filter(inclusion, imgincl_rsfmri_include==1, eventname=='2_year_follow_up_y_arm_1')
inclusion_filtered = dplyr::select(inclusion_filtered, src_subject_id, eventname, imgincl_rsfmri_include)

#including the functional data
nacc_filtered=nacc_filtered[complete.cases(nacc_filtered),]
count(nacc_filtered)

final_combo = full_join(nacc_filtered, final_combo, by=('src_subject_id'))
final_combo=final_combo[complete.cases(final_combo),]
count(final_combo)

#including the functional QC inclusion info into the mix
inclusion_filtered=inclusion_filtered[complete.cases(inclusion_filtered),]
count(inclusion_filtered)

final_combo = full_join(inclusion_filtered, final_combo, by=('src_subject_id'))
final_combo=final_combo[complete.cases(final_combo),]
count(final_combo)

```

```{r Scanner ID}

#gathering covariates and random effects

#scanner serial number
covariates = read.csv("ABCDdatadir/core/imaging/mri_y_adm_info.csv",header=TRUE,stringsAsFactors = FALSE)
table(covariates$eventname)

scannerid = filter(covariates, eventname=='2_year_follow_up_y_arm_1')
scannerid_USE = dplyr::select(scannerid, src_subject_id, eventname, mri_info_deviceserialnumber)

#excluding youth who were scanned on 000000000UM750MR & HASH31ce566d since there were only 12 participants combined
scannerid_USE = dplyr::filter(scannerid_USE, mri_info_deviceserialnumber != "000000000UM750MR")
scannerid_USE = dplyr::filter(scannerid_USE, mri_info_deviceserialnumber != "HASH31ce566d")

#including scanner ID into the mix
scannerid_USE=scannerid_USE[complete.cases(scannerid_USE),]
count(scannerid_USE)

final_combo = full_join(scannerid_USE, final_combo, by=('src_subject_id'))
final_combo=final_combo[complete.cases(final_combo),]
count(final_combo)

```

```{r Race/ethnicity, Parent education, and Sex}

#Pulling race/ethnicity, parent education, and sex
r_et_income = read.csv("ABCDdatadir/core/abcd-general/abcd_p_demo.csv",header=TRUE,stringsAsFactors = FALSE)
table(r_et_income$eventname)

demoincome = filter(r_et_income, eventname=='baseline_year_1_arm_1')
demoincome_USE = dplyr::select(demoincome, src_subject_id, eventname, demo_prnt_ed_v2, demo_sex_v2, race_ethnicity)

demoincome_USE$demo_sex_v2 <- car::recode(demoincome_USE$demo_sex_v2, "3=1; 4=2")

#making race/ethnicity as a factor
demoincome_USE$race_ethnicity = as.factor(demoincome_USE$race_ethnicity)

#Recoding for numbers 0-8 to be #1 for less than high school education
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 0] <- 1
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 1] <- 1
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 2] <- 1
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 3] <- 1
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 4] <- 1
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 5] <- 1
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 6] <- 1
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 7] <- 1
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 8] <- 1

#Recoding for numbers 9-12 to be #2 for some high school
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 9] <- 2
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 10] <- 2
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 11] <- 2
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 12] <- 2

#Recoding for numbers 13-14 to be #3 for high school graduate or GED
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 13] <- 3
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 14] <- 3

#Recoding for numbers 15-17 to be #4 for between hs grad and bachelor
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 15] <- 4
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 16] <- 4
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 17] <- 4

#Recoding for number 18 to be #5 for bachelor's degree
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 18] <- 5

#Recoding for number 19-20 to be #6 for master's degree and professional
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 19] <- 6

#Recoding for number 21 to be #7 for doctorate
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 20] <- 7
demoincome_USE$demo_prnt_ed_v2[demoincome_USE$demo_prnt_ed_v2 == 21] <- 7

#Coding 777 and 999 as NA
demoincome_USE[demoincome_USE==777] <- NA
demoincome_USE[demoincome_USE==999] <- NA

#centering sex
demoincome_USE$demo_sex_v2 = scale(demoincome_USE$demo_sex_v2, center = TRUE, scale = FALSE)
table(demoincome_USE$demo_sex_v2)

colnames(demoincome_USE)
demoincome_USE=demoincome_USE[c("demo_prnt_ed_v2", "demo_sex_v2", "race_ethnicity", "src_subject_id", "eventname")]
demoincome_USE=demoincome_USE[complete.cases(demoincome_USE),]
count(demoincome_USE)

final_combo = full_join(demoincome_USE, final_combo, by=('src_subject_id'))
final_combo=final_combo[complete.cases(final_combo),]
count(final_combo)

```

```{r Age & Fam ID}

#Pulling in family ID and Age
age_famid = read.csv("ABCDdatadir/core/abcd-general/abcd_y_lt.csv",header=TRUE,stringsAsFactors = FALSE)
table(age_famid$eventname)

fam_id = filter(age_famid, eventname=='baseline_year_1_arm_1')
fam_id_USE = dplyr::select(fam_id, src_subject_id, eventname, rel_family_id)

age = filter(age_famid, eventname=='2_year_follow_up_y_arm_1')
age_USE = dplyr::select(age, src_subject_id, eventname, interview_age)

#including Family ID
fam_id_USE=fam_id_USE[complete.cases(fam_id_USE),]
count(fam_id_USE)

final_combo = full_join(fam_id_USE, final_combo, by=('src_subject_id'))
final_combo=final_combo[complete.cases(final_combo),]
count(final_combo)

#including Age
age_USE=age_USE[complete.cases(age_USE),]
count(age_USE)
#10,972

final_combo = full_join(age_USE, final_combo, by=('src_subject_id'))
final_combo=final_combo[complete.cases(final_combo),]
count(final_combo)

```

```{r Analysis Prep}

table(final_combo$ACE_score)

#colnames(final_combo)
final_combo$rel_family_id = as.factor(final_combo$rel_family_id)

#making ACE score and PDS avg numeric
final_combo$ACE_score = as.numeric(final_combo$ACE_score)
final_combo$pds_avg = as.numeric(final_combo$pds_avg)
colnames(final_combo)

final_combo = final_combo[complete.cases(final_combo),]
final_combo = data.frame(final_combo)

write.csv(final_combo, "final_combo.csv")

```

```{r lNAcc-DMN analysis}

#if the lmerTest is loaded, you will need to unload it with:
detach("package:lmerTest")

fit.mediator = lmer(pds_avg ~ ACE_score*demo_sex_v2 + (1 | rel_family_id) + mri_info_deviceserialnumber + interview_age + race_ethnicity + demo_prnt_ed_v2, data=final_combo)
fit.dv = lmer(rsfmri_cor_ngd_df_scs_aalh ~ ACE_score*demo_sex_v2 + pds_avg + (1 | rel_family_id) + mri_info_deviceserialnumber + interview_age + race_ethnicity + demo_prnt_ed_v2, data=final_combo)

#will give the overall effect - this is for ACES 0 vs 4+
#note this will take a while
#results may not exactly match paper due to bootstrapping
results <- mediate(fit.mediator, fit.dv, treat="ACE_score", mediator = "pds_avg", treat.value = 3.35682132963989, control.value = -0.643178670360111)
summary(results)

#this is for the rest of the ace levels since this model is significant - 0-3
results.l.dmn.ace3 <- mediation::mediate(fit.mediator, fit.dv, treat="ACE_score", mediator = "pds_avg", control.value = -0.643178670360111, treat.value = 2.35682132963989)
summary(results.l.dmn.ace3)

#0-2
results.l.dmn.ace2 <- mediation::mediate(fit.mediator, fit.dv, treat="ACE_score", mediator = "pds_avg", control.value = -0.643178670360111, treat.value = 1.35682132963989)
summary(results.l.dmn.ace2)

#0-1
results.l.dmn.ace1 <- mediation::mediate(fit.mediator, fit.dv, treat="ACE_score", mediator = "pds_avg", control.value = -0.643178670360111, treat.value = 0.356821329639889)
summary(results.l.dmn.ace1)

```

```{r rNAcc-DMN analysis}

fit.mediator = lmer(pds_avg ~ ACE_score*demo_sex_v2 + (1 | rel_family_id) + mri_info_deviceserialnumber + interview_age + race_ethnicity + demo_prnt_ed_v2, data=final_combo)
fit.dv = lmer(rsfmri_cor_ngd_df_scs_aarh ~ ACE_score*demo_sex_v2 + pds_avg + (1 | rel_family_id) + mri_info_deviceserialnumber + interview_age + race_ethnicity + demo_prnt_ed_v2, data=final_combo)

#will give overall effect
#note this will take a while
#results may not exactly match paper due to bootstrapping
results <- mediate(fit.mediator, fit.dv, treat="ACE_score", mediator = "pds_avg", treat.value = 3.35682132963989, control.value = -0.643178670360111)
summary(results)

```

```{r lNAcc-FPN analysis}

fit.mediator = lmer(pds_avg ~ ACE_score*demo_sex_v2 + (1 | rel_family_id) + mri_info_deviceserialnumber + interview_age + race_ethnicity + demo_prnt_ed_v2, data=final_combo)
fit.dv = lmer(rsfmri_cor_ngd_fopa_scs_aalh ~ ACE_score*demo_sex_v2 + pds_avg + (1 | rel_family_id) + mri_info_deviceserialnumber + interview_age + race_ethnicity + demo_prnt_ed_v2, data=final_combo)

#will give overall effect
#note this will take a while
#results may not exactly match paper due to bootstrapping
results <- mediate(fit.mediator, fit.dv, treat="ACE_score", mediator = "pds_avg", treat.value = 3.35682132963989, control.value = -0.643178670360111)
summary(results)

```

```{r rNAcc-FPN analysis}

fit.mediator = lmer(pds_avg ~ ACE_score*demo_sex_v2 + (1 | rel_family_id) + mri_info_deviceserialnumber + interview_age + race_ethnicity + demo_prnt_ed_v2, data=final_combo)
fit.dv = lmer(rsfmri_cor_ngd_fopa_scs_aarh ~ ACE_score*demo_sex_v2 + pds_avg + (1 | rel_family_id) + mri_info_deviceserialnumber + interview_age + race_ethnicity + demo_prnt_ed_v2, data=final_combo)

#will give me overall effect
#note this will take a while
#results may not exactly match paper due to bootstrapping
results <- mediate(fit.mediator, fit.dv, treat="ACE_score", mediator = "pds_avg", treat.value = 3.35682132963989, control.value = -0.643178670360111)
summary(results)
```


```{r lmer output}

#lmerTest doesn't play nice with mediate, so need to run separately
library(lmerTest)

fit.mediator = lmer(pds_avg ~ ACE_score*demo_sex_v2 + (1 | rel_family_id) + mri_info_deviceserialnumber + interview_age + race_ethnicity + demo_prnt_ed_v2, data=final_combo)
summary(fit.mediator)

fit.dv.dflh = lmer(rsfmri_cor_ngd_df_scs_aalh ~ ACE_score*demo_sex_v2 + pds_avg + (1 | rel_family_id) + mri_info_deviceserialnumber + interview_age + race_ethnicity + demo_prnt_ed_v2, data=final_combo)
summary(fit.dv.dflh)

fit.dv.dfrh = lmer(rsfmri_cor_ngd_df_scs_aarh ~ ACE_score*demo_sex_v2 + pds_avg + (1 | rel_family_id) + mri_info_deviceserialnumber + interview_age + race_ethnicity + demo_prnt_ed_v2, data=final_combo)
summary(fit.dv.dfrh)

fit.dv.fopa.lh = lmer(rsfmri_cor_ngd_fopa_scs_aalh ~ ACE_score*demo_sex_v2 + pds_avg + (1 | rel_family_id) + mri_info_deviceserialnumber + interview_age + race_ethnicity + demo_prnt_ed_v2, data=final_combo)
summary(fit.dv.fopa.lh)

fit.dv.fopa.rh = lmer(rsfmri_cor_ngd_fopa_scs_aarh ~ ACE_score*demo_sex_v2 + pds_avg + (1 | rel_family_id) + mri_info_deviceserialnumber + interview_age + race_ethnicity + demo_prnt_ed_v2, data=final_combo)
summary(fit.dv.fopa.rh)
```
